---
name: 'Standard CI Test'
description: 'Run an AWX Standard CI Test'
inputs:
  test_command:
    description: 'The command the test should run'
    required: true
  label:
    description: 'The label for the step we run'
    required: true
  token:
    description: 'Set to ${{ secrets.GITHUB_TOKEN }}'
    required: True
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Get python version from Makefile
      run: echo py_version=`make PYTHON_VERSION` >> $GITHUB_ENV
      shell: bash

    - name: Install python ${{ env.py_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.py_version }}

    - name: Log in to registry
      run: |
        echo "${{ token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash

    - name: Pre-pull image to warm build cache
      run: |
        docker pull ghcr.io/${{ github.repository_owner }}/awx_devel:${{ env.BRANCH }} || :
      shell: bash

    - name: Build image
      run: |
        DEV_DOCKER_TAG_BASE=ghcr.io/${{ github.repository_owner }} COMPOSE_TAG=${{ env.BRANCH }} make docker-compose-build
      shell: bash

    - name: ${{ inputs.label }}
      run: |
        docker run -u $(id -u) --rm -v ${{ github.workspace}}:/awx_devel/:Z \
          --workdir=/awx_devel ghcr.io/${{ github.repository_owner }}/awx_devel:${{ env.BRANCH }} ${{ inputs.test_command }}
      shell: bash
